# Generated by Django 5.1.3 on 2024-12-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_footballplayer_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ad_Id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
