# Generated by Django 5.1.3 on 2024-12-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_car_ad_id_alter_car_fuel_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ad_Id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='ad_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='ad_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption',
            field=models.FloatField(default=0.0),
        ),
    ]
