# Generated by Django 5.1.3 on 2024-12-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_car_ad_id_alter_car_ad_date_alter_car_ad_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.CharField(max_length=255),
        ),
    ]
