# Generated by Django 5.1.3 on 2024-12-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_car_engine_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_tank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='trade_in',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
