# Generated by Django 5.1.3 on 2025-01-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_car_engine_capacity_alter_car_fuel_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_file', models.FileField(upload_to='voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
