# Generated by Django 5.1.3 on 2024-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ad_Id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_date', models.DateField()),
                ('ad_neighborhood', models.CharField(max_length=100)),
                ('ad_district', models.CharField(max_length=100)),
                ('ad_province', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('engine_power', models.IntegerField()),
                ('engine_capacity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=50)),
                ('ad_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ad_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('match_day', models.IntegerField()),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
