# Generated by Django 5.1.3 on 2024-11-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='league',
            field=models.CharField(choices=[('Premier League', 'Premier League'), ('La Liga', 'La Liga'), ('Bundesliga', 'Bundesliga'), ('Serie A', 'Serie A')], default='Premier League', max_length=20),
            preserve_default=False,
        ),
    ]
