from django.db import models  # type: ignore

class Car(models.Model):
    ad_Id = models.IntegerField()
    ad_date = models.CharField(max_length=255)
    ad_loc1 = models.CharField(max_length=255)
    ad_loc2 = models.CharField(max_length=255)
    brand = models.CharField(max_length=255)
    series = models.CharField(max_length=255)
    model = models.CharField(max_length=255)
    year = models.CharField(max_length=255)
    mileage = models.CharField(max_length=255)
    transmission = models.CharField(max_length=255)
    fuel_type = models.CharField(max_length=255)
    body_type = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    engine_capacity = models.CharField(max_length=255)
    engine_power = models.CharField(max_length=255)
    drive_type = models.CharField(max_length=255)
    vehicle_condition = models.CharField(max_length=255)
    fuel_consumption = models.CharField(max_length=255)
    fuel_tank = models.CharField(max_length=255)
    paint_replacement = models.CharField(max_length=255)
    trade_in = models.CharField(max_length=255)
    seller_type = models.CharField(max_length=255)
    seller_name = models.CharField(max_length=255)
    ad_price = models.CharField(max_length=255)
    ad_url = models.URLField()

class FootballGame(models.Model):
    Wk = models.FloatField(null=True) 
    Day = models.CharField(max_length=255)
    Date = models.CharField(max_length=255)  
    Time = models.CharField(max_length=255) 
    Home = models.CharField(max_length=255)
    Away = models.CharField(max_length=255)
    Score = models.CharField(max_length=255)
    xG = models.FloatField()
    xG_1 = models.FloatField()
    season = models.CharField(max_length=255)
    game_id = models.FloatField(null=True) 

class FootballPlayer(models.Model):
    index = models.IntegerField(unique=True)
    Player = models.CharField(max_length=255)
    number = models.FloatField(null=True)  
    Nation = models.CharField(max_length=255)
    Pos = models.CharField(max_length=255)
    Age = models.CharField(max_length=255, null=True)  
    Min = models.FloatField(null=True)
    Gls = models.FloatField(null=True)
    Ast = models.FloatField(null=True)
    PK = models.FloatField(null=True)
    PKatt = models.FloatField(null=True)
    Sh = models.FloatField(null=True)
    SoT = models.FloatField(null=True)
    CrdY = models.FloatField(null=True)
    CrdR = models.FloatField(null=True)
    Touches = models.FloatField(null=True)
    Tkl = models.FloatField(null=True)
    Int = models.FloatField(null=True)
    Blocks = models.FloatField(null=True)
    xG = models.FloatField(null=True)
    npxG = models.FloatField(null=True)
    xAG = models.FloatField(null=True)
    SCA = models.FloatField(null=True)
    GCA = models.FloatField(null=True)
    Cmp_x = models.FloatField(null=True)
    Att_x = models.FloatField(null=True)
    Cmp_pct_x = models.FloatField(null=True)
    PrgP = models.FloatField(null=True)
    Carries = models.FloatField(null=True)
    PrgC = models.FloatField(null=True)
    Att_x_alt = models.FloatField(null=True)
    Succ = models.FloatField(null=True)
    SoTA = models.FloatField(null=True)
    GA = models.FloatField(null=True)
    Saves = models.FloatField(null=True)
    Save_pct = models.FloatField(null=True)
    PSxG = models.FloatField(null=True)
    Cmp_y = models.FloatField(null=True)
    Att_y = models.FloatField(null=True)
    Cmp_pct_y = models.FloatField(null=True)
    Att_GK = models.FloatField(null=True)
    Thr = models.FloatField(null=True)
    Launch_pct = models.FloatField(null=True)
    AvgLen = models.FloatField(null=True)
    Opp = models.FloatField(null=True)
    Stp = models.FloatField(null=True)
    Stp_pct = models.FloatField(null=True)
    AvgDist = models.FloatField(null=True)
    home = models.IntegerField(null=True)
    game_id = models.IntegerField()
    Cmp = models.FloatField(null=True)
    Att = models.FloatField(null=True)
    Cmp_pct = models.FloatField(null=True)
    Att_alt = models.FloatField(null=True)  



class Voice(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    audio_file = models.FileField(upload_to='voices/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name or f"Voice {self.id}"
