from django.db import models

class Car(models.Model):
    ad_id = models.AutoField(primary_key=True)
    ad_date = models.DateField()
    ad_neighborhood = models.CharField(max_length=100)
    ad_district = models.CharField(max_length=100)
    ad_province = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    series = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year = models.IntegerField()
    mileage = models.IntegerField()
    fuel_type = models.CharField(max_length=50)
    transmission = models.CharField(max_length=50)
    body_type = models.CharField(max_length=50)
    engine_power = models.IntegerField()
    engine_capacity = models.IntegerField()
    color = models.CharField(max_length=50)
    ad_price = models.DecimalField(max_digits=10, decimal_places=2)
    ad_url = models.URLField()
